# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {
#     "name":"Ri",
#     "number": "9912991214"
# }

GET http://localhost:3001

# DELETE  http://localhost:3001/api/notes/6164598f0fc3ce11d6929bc5