# POST http://localhost:3001/api/notes
# Content-Type: application/json

# {
#     "content": "hello",
#     "date": "",
#     "important": true,
# }

GET http://localhost:3001/api/notes

# DELETE  http://localhost:3001/api/notes/6164598f0fc3ce11d6929bc5